version: '3'
services:
  couchbase:
    image: bentonam/couchbase-docker:enterprise-4.6.3
    container_name: testing-couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      NODE_TYPE: DEFAULT
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: password
      CLUSTER_NAME: Testing Cluster
      SERVICES: data
      CLUSTER_RAMSIZE: 500
      BUCKET: testing
      BUCKET_RAMSIZE: 500
      ENABLE_FLUSH: 1